spring.datasource.url=jdbc:postgresql://dpg-d71qhqvdiees73buvf40-a/database_56ef


spring.datasource.username=database_56ef_user
spring.datasource.password=dJ6sx654uNFx0EPbKNVMUvDOcbhtR04E


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

